name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_build:
    name: Ubuntu Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          default: true
          override: true
    - name: run tests
      env:
          RUST_TEST_TASKS: 1
      run: cargo test --all-features

  windows_build:
    name: Windows Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          default: true
          override: true
    - name: run tests
      env:
          RUST_TEST_TASKS: 1
      run: cargo test --all-features
